---
title: "tidytuesday-3.30"
author: "Yiyun Sun"
date: "3/31/2021"
output: html_document
---
```{r}
library(tidyverse)
```

```{r}
allshades <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-30/allShades.csv')

```

```{r}
allshades <- allshades %>%
  drop_na() %>% 
  mutate(n = row_number())

allshades_total<- allshades %>% 
  group_by(brand) %>% 
  summarize(total=n())

allshades_clean<- allshades %>% 
  left_join(allshades_total, by = "brand")

```

```{r}
allshades_clean %>% 
  ggplot() + 
  geom_bar(aes(x = fct_reorder(brand, total), group = n,fill = hex))
```




```{r}
bareMinerals <- allshades %>%
  filter(brand == "bareMinerals") %>%
  arrange(desc(lightness)) %>%
  select(product, lightness, hex) %>%
  mutate(value = 1)
```

```{r}
bareMinerals %>%
  ggplot(aes(x="", y = value, fill = hex)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start=0) +
  scale_fill_manual(values = bareMinerals$hex, guide = F) +
  labs(
    subtitle = "bareMinerals"
  ) 

```












